# pyrefly: ignore [missing-import]
from google import genai
# pyrefly: ignore [missing-import]
from google.genai import types
from app.config import Config
from app.models import GeminiInsights, GeminiDailyInsight, GeminiBusinessActions

class GeminiService:
    def __init__(self):
        try:
            # Initialize the official Google GenAI SDK client
            self.client = genai.Client(api_key=Config.GEMINI_API_KEY)
        except Exception as e:
            # Fall back to None if initialization fails (e.g. invalid key formatting)
            self.client = None
            print(f"⚠️ Warning: Failed to initialize Gemini GenAI client: {str(e)}")

    def generate_strategic_insights(
        self, 
        history_dates: list[str], 
        history_occupancy: list[float], 
        forecast_dates: list[str], 
        forecast_occupancy: list[float],
        forecast_context: dict = None
    ) -> GeminiInsights:
        """
        Sends historical and forecasted hotel occupancy data to Gemini,
        generating structured strategic business reasoning (GeminiInsights) with minimal token footprint.
        Accepts optional forecast_context (exogenous covariates like holidays/promotions) to guide reasoning.
        """
        if not self.client:
            return self.get_fallback_insights("Gemini API Client not initialized.")

        # Build clean data representation for the model prompt
        history_payload = "\n".join(
            [f"{date}: {occ}%" for date, occ in zip(history_dates, history_occupancy)]
        )
        forecast_payload = "\n".join(
            [f"{date}: {occ}%" for date, occ in zip(forecast_dates, forecast_occupancy)]
        )

        context_payload = ""
        if forecast_context:
            import json
            context_payload = (
                "\n======================================================\n"
                "FORECAST CONTEXT (Holidays, Promotions, Events, & Static Metadata)\n"
                "======================================================\n"
                f"{json.dumps(forecast_context, indent=2)}\n"
            )

        prompt = f"""
You are GeoBoost's AI Revenue Manager.
Your job is to provide business reasoning and recommendations for hotel managers based on timeseries occupancy data.

Here is the historical hotel occupancy data:
{history_payload}

Here is the 7-day forecasted hotel occupancy generated by TimesFM:
{forecast_payload}
{context_payload}

======================================================
RULES FOR COMPLIANCE
======================================================
1. Base every insight ONLY on the supplied historical data, forecast, and any provided forecast context.
2. Do not invent events, holidays, weather, or market conditions that are not present in the provided forecast context or timeseries.
3. If something cannot be inferred from the data or context, state that it is "unknown".
4. Keep recommendations practical, business-oriented, and tailored to the provided context.
5. Return ONLY valid JSON matching the schema. Do not return markdown, explaining text, or HTML.

======================================================
PROMPT CONSTRAINT (TOKEN REDUCTION & CONCISENESS)
======================================================
- summary: Exactly 2-3 short sentences summarizing the overall business outlook.
- daily_insights: Generate exactly 7 objects (one for EACH forecast day in chronological order).
  - headline: Short headline (<= 5 words).
  - summary: Extremely short summary of this day's business context (<= 40 words).
  - recommended_action: One specific, actionable operation step.
  - risk: One operational risk/challenge.
  - dashboard_badge: Must be one of: "Monitor", "Prepare", "Optimize", "Peak", "Critical".
- business_actions:
  - pricing: One short sentence describing pricing action/reason.
  - staffing: One short sentence describing staffing action/reason.
  - inventory: One short sentence describing inventory action/reason.
  - marketing: One short sentence describing marketing action/reason.

Do NOT include or repeat dates, occupancy numbers, upper/lower bounds, or mathematical metrics in your text responses unless directly relevant. Let the backend handle the calculations.
"""

        try:
            # Request structured JSON matching the Pydantic schema
            response = self.client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=GeminiInsights,
                    temperature=0.1,
                ),
            )
            
            import json
            data = json.loads(response.text)
            return GeminiInsights(**data)

        except Exception as e:
            print(f"❌ Error generating Gemini insights: {str(e)}")
            return self.get_fallback_insights(f"Failed to generate insights: {str(e)}")

    def get_fallback_insights(self, reason: str) -> GeminiInsights:
        """Helper to return clean empty schema if model generation fails."""
        default_actions = GeminiBusinessActions(
            pricing="Hold standard pricing due to lack of analytical data.",
            staffing="Schedule standard operational shifts.",
            inventory="Maintain baseline amenity stock levels.",
            marketing="Run standard local awareness campaigns."
        )
        default_insights = [
            GeminiDailyInsight(
                headline="Standby Mode",
                summary="Awaiting data synchronization and analysis completion.",
                recommended_action="Conduct routine daily maintenance.",
                risk="Lack of predictive visibility.",
                dashboard_badge="Monitor"
            ) for _ in range(7)
        ]
        return GeminiInsights(
            summary=f"Occupancy insights currently unavailable. Reason: {reason}",
            daily_insights=default_insights,
            business_actions=default_actions
        )


