from pydantic import BaseModel
from typing import List

class ForecastItem(BaseModel):
    date: str
    predicted_occupancy: float
    lower_bound: float
    upper_bound: float

# --- Schemas generated by Gemini (Light Business Reasoning) ---

class GeminiDailyInsight(BaseModel):
    headline: str
    summary: str  # <= 40 words
    recommended_action: str
    risk: str
    dashboard_badge: str  # "Monitor" | "Prepare" | "Optimize" | "Peak" | "Critical"

class GeminiBusinessActions(BaseModel):
    pricing: str
    staffing: str
    inventory: str
    marketing: str

class GeminiInsights(BaseModel):
    summary: str  # 2-3 short sentences
    daily_insights: List[GeminiDailyInsight]
    business_actions: GeminiBusinessActions

# --- Schemas returned by API (Merged Backend + Gemini) ---

class KPIs(BaseModel):
    average_occupancy: float
    peak_occupancy: float
    peak_day: str
    growth_percent: float
    trend: str  # "Increasing" | "Decreasing" | "Stable"

class MergedDailyInsight(BaseModel):
    date: str
    day: str
    predicted_occupancy: float
    lower_bound: float
    upper_bound: float
    status: str
    priority: str
    headline: str
    summary: str
    recommended_action: str
    risk: str
    dashboard_badge: str

class BusinessActions(BaseModel):
    pricing: str
    staffing: str
    inventory: str
    marketing: str

class ForecastResponse(BaseModel):
    forecast: List[ForecastItem]
    records_analyzed: int
    kpis: KPIs
    summary: str  # Maps to Gemini's summary
    daily_insights: List[MergedDailyInsight]
    business_actions: BusinessActions





